apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fmg64q4eq-go 
  janus-idp.io/tekton: fmg64q4eq-go
  backstage.io/kubernetes-id: fmg64q4eq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fmg64q4eq-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml