apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fmg64q4eq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fmg64q4eq-go 
  name: fmg64q4eq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fmg64q4eq-go 
